name: 'GRPC composite action'
description: 'A composite action to handle building and uploading GRPC artifactes for python and CPP'

inputs:
  new-tag:
    required: true
    description: 'The new tag to push'
  proto-folder:
    required: true
    description: 'Path to protofile'
    default: './'
  proto-file:
      required: true
      description: 'protofile name'
  arch:
    required: true
    description: 'The package arch'
    default: x86_64
    
outputs:
  package:
    description: 'The new package name and version'
    value: ${{ steps.echo_name.outputs.package-name }}
    
runs:
    using: "composite"
    steps:
      - name: Compile proto file for CPP
        working-directory: ${{ inputs.proto-folder }}/cpp-generated
        run: |
          protoc -I=. --proto_path=./ --cpp_out=./ ../${{ inputs.proto-file }}
          protoc -I=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_cpp_plugin` --proto_path=.. ../${{ inputs.proto-file }}
              
      - name: Upload compiled proto files
        uses: actions/upload-artifact@v2
        with:
          name: cpp_generated
          path: ./cpp-generated

      - name: Compile proto file for Python
        working-directory: ${{ inputs.proto-folder }}/python-generated
        run: |
          protoc -I=. --proto_path=./ --python_out=./ ../${{ inputs.proto-file }}
          protoc -I=. --grpc_out=. --plugin=protoc-gen-grpc=`which grpc_python_plugin` --proto_path=.. ../${{ inputs.proto-file }}

      - name: Upload compiled proto files
        uses: actions/upload-artifact@v2
        with:
          name: python_generated
          path: ./python-generated

      # - name: Echo package name
      #   id: echo_name
      #   shell: bash
      #   run: |
      #     echo \"$(tac ${{ inputs.package-folder }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\"
      #     echo "::set-output name=package-name:: \
      #     $(echo \"$(tac ${{ inputs.package-folder }}conanfile.py | grep -e 'name =' -e '__version__ =' | awk -F"[\"\"]" '{printf $2"/"}' | cut -d "/" -f 1,2)\")"
